# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61ec67df9cbcf7fdd4276662855b881044c74f649846869107f3f175ed8fd5b2f3c12fd1910b1ea68844e07f8f3781273c3c7f54705719a95fcc30ea8101b31b

test:
  secret_key_base: 8587423df15ac63c3d822844282ba8701c338a1a0d6661f570506dcbbbc08ee4b99cafc94f5d88722e194ffab0df79e4a9f6f270459bea4fa4b2e46f1e90cfab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
